# Generated by Django 5.0.3 on 2024-03-14 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="TipoVehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, null=True)),
                ("anio", models.IntegerField(null=True)),
                ("precio", models.IntegerField(null=True)),
                ("imagen", models.CharField(max_length=50, null=True)),
                (
                    "marca",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehiculos.marca",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehiculos.tipovehiculo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FichaVehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo_principal", models.CharField(max_length=50)),
                ("descrip_principal", models.TextField(max_length=120)),
                ("titulo2", models.CharField(max_length=50)),
                ("descrip2", models.TextField(max_length=120)),
                ("titulo3", models.CharField(max_length=50)),
                ("descrip3", models.TextField(max_length=120)),
                ("img_principal", models.CharField(max_length=50)),
                ("img_2", models.CharField(max_length=50)),
                ("img_3", models.CharField(max_length=50)),
                (
                    "nombre",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehiculos.vehiculo",
                    ),
                ),
            ],
        ),
    ]
